### PR TITLE
Added Routing

### PR DESCRIPTION
**Pull request by romabulani**
- Routing to all Pages
- Some modification in styles
- Improvised folder structure for imports and exports

### CODE REVIEW

**Review by anuj-kumary — APPROVED** [review]
Clean code and liked the naming convention

**Review by manish591 — APPROVED** [review]
Everything is looking good,
Now, using index js export your code is looking cleaner

**Review by Rohanmond — APPROVED** [review]
Code is looking good.

**Review by lomesshh — APPROVED** [review]
Nicely done
very neat & clean code !

**Pull request merged**
